version: "3.9"

services:

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"   # Phoenix UI
      - "4317:4317"   # OTLP gRPC for tracing
    networks:
      - net

  image_agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      ENV: docker
      PHOENIX_ENDPOINT: http://phoenix:4317
      OTEL_EXPORTER_OTLP_ENDPOINT: http://phoenix:4317
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./test_images:/app/test_images
    networks:
      - net

networks:
  net:
    driver: bridge
